ARG APP_HOST="0.0.0.0"
ARG APP_PORT="8080"
ARG APP_WITH_SSL="false"
ARG NODE_VERSION="20.9.0"
ARG NPME_REGISTRY="https://npme.walmart.com/"
ARG YARN_REGISTRY="https://npme.walmart.com/"
ARG ALPINE_VERSION="3.17"

FROM docker.prod.walmart.com/wce/ca-roots:latest as roots

FROM hub.docker.prod.walmart.com/library/node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS base
    #### base: repos
    ARG ALPINE_VERSION
    RUN echo '' > /etc/apk/repositories
    RUN echo "http://ark-repos.wal-mart.com/ark/apk/published/alpine/${ALPINE_VERSION}/direct/soe/noenv/main/" >> /etc/apk/repositories
    RUN echo "http://ark-repos.wal-mart.com/ark/apk/published/alpine/${ALPINE_VERSION}/direct/soe/noenv/community/" >> /etc/apk/repositories

    #### base: copying certs from walmart docker repository
    COPY --from=roots /usr/local/share/ca-certificates /usr/local/share/ca-certificates
    COPY --from=roots /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
    RUN rm -f /etc/ssl/cert.pem && ln -s /etc/ssl/certs/ca-certificates.crt /etc/ssl/cert.pem
    ENV NODE_EXTRA_CA_CERTS=/etc/ssl/cert.pem
    ENV DANGEROUSLY_DISABLE_HOST_CHECK=true

    ## creating the user and group with a higher ID
    RUN addgroup -S -g 10001 app
    RUN adduser -S -D -u 10000 -s /sbin/nologin -h /opt/app -G app app
    RUN chown -R app:app /opt/app

    #### base: update/upgrade pkgs
    RUN apk update && apk upgrade

    #### base: install/configure packages
    RUN apk --no-cache add jq tini findutils bash
    RUN rm -rf /var/cache/* && mkdir /var/cache/apk

    ENTRYPOINT ["/sbin/tini", "--"]

FROM base AS deps
    ARG NPME_REGISTRY
    ARG YARN_REGISTRY
    WORKDIR /opt/app

    #### deps: move package files

    COPY ./package.json ./package-lock.json ./
    COPY ./.scripts ./.scripts
    
   #### deps: install deps
    RUN npm --version
    RUN npm install

    # Fix permissions for node_modules
     RUN chown -R app:app /opt/app/node_modules

    # RUN mkdir -p /opt/app/node_modules/.cache/.eslintcache && chown -R app:app /opt/app/node_modules/.cache

    # RUN mkdir -p /opt/app/node_modules/.cache/.eslintcache/.cache_1jgaxxd && \
    #     chown -R app:app /opt/app/node_modules/.cache/.eslintcache
    

FROM base AS builder
    ARG APP_HOST
    ARG APP_PORT
    ARG APP_WITH_SSL

    ENV HOST=${APP_HOST}
    ENV PORT=${APP_PORT}
    ENV WITH_SSL=${APP_WITH_SSL}
   
    WORKDIR /opt/app

    COPY --from=deps /opt/app .
    COPY ./public ./public
    COPY ./src ./src

    # Fix permissions for node_modules
 

    RUN npm build


FROM base AS runner
    WORKDIR /opt/app

    ARG APP_HOST
    ARG APP_PORT
    ARG APP_WITH_SSL

    ENV HOST=${APP_HOST}
    ENV PORT=${APP_PORT}
    ENV WITH_SSL=${APP_WITH_SSL}

    COPY --from=builder /opt/app/ ./
    RUN chown -R 10000:10000 /opt/app/node_modules
    EXPOSE 8080

    # switch to app user
    USER 10000
    COPY --chown=10000:10001 . .
    ## start app
    CMD ["npm", "start"]
    